const styles = {
  page: {
    minHeight: "100vh",
    background: "#F4F1EC",
    color: "#2B2F2E",
    padding: "30px",
    fontFamily: "Inter, Arial, sans-serif",
  },
  shell: {
    maxWidth: "1000px",
    margin: "0 auto",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    gap: "20px",
    alignItems: "center",
    marginBottom: "20px",
  },
  title: {
    margin: 0,
    fontSize: "42px",
  },
  subtitle: {
    color: "#5A5F5D",
    marginTop: "6px",
  },
  authCard: {
    maxWidth: "420px",
    margin: "80px auto",
    background: "#FBFAF8",
    padding: "28px",
    borderRadius: "16px",
    boxShadow: "0 10px 30px rgba(0,0,0,0.08)",
  },
  cartCard: {
    background: "#FBFAF8",
    border: "2px solid #7FAF8E",
    padding: "20px",
    borderRadius: "16px",
    marginBottom: "20px",
  },
  createCard: {
    background: "#FBFAF8",
    padding: "20px",
    borderRadius: "16px",
    marginBottom: "20px",
  },
  boxCard: {
    background: "#FBFAF8",
    border: "1px solid #D6D2CB",
    borderRadius: "16px",
    padding: "20px",
    marginTop: "20px",
  },
  boxHeader: {
    display: "flex",
    justifyContent: "space-between",
    gap: "16px",
    alignItems: "flex-start",
    borderBottom: "1px solid #D6D2CB",
    paddingBottom: "14px",
    marginBottom: "14px",
  },
  boxTitle: {
    margin: "0 0 8px 0",
    fontSize: "24px",
  },
  sectionTitle: {
    marginTop: 0,
  },
  panel: {
    background: "#FFFFFF",
    border: "1px solid #E7E2DA",
    borderRadius: "12px",
    padding: "16px",
    marginTop: "14px",
  },
  subPanel: {
    background: "#F4F1EC",
    border: "1px solid #D6D2CB",
    borderRadius: "12px",
    padding: "14px",
    marginTop: "12px",
  },
  cartItem: {
    background: "#FFFFFF",
    border: "1px solid #E7E2DA",
    borderRadius: "12px",
    padding: "14px",
    marginTop: "12px",
  },
  itemCard: {
    borderTop: "1px solid #E7E2DA",
    paddingTop: "12px",
    marginTop: "12px",
  },
  itemImage: {
    width: "130px",
    display: "block",
    marginTop: "8px",
    borderRadius: "10px",
  },
  row: {
    display: "flex",
    gap: "10px",
    flexWrap: "wrap",
    alignItems: "center",
  },
  input: {
    display: "block",
    width: "100%",
    maxWidth: "360px",
    padding: "10px",
    margin: "8px 0",
    border: "1px solid #D6D2CB",
    borderRadius: "8px",
  },
  textarea: {
    display: "block",
    width: "100%",
    maxWidth: "520px",
    minHeight: "80px",
    padding: "10px",
    margin: "8px 0",
    border: "1px solid #D6D2CB",
    borderRadius: "8px",
  },
  fileInput: {
    display: "block",
    margin: "10px 0",
  },
  checkboxLabel: {
    display: "block",
    marginBottom: "8px",
  },
  primaryButton: {
    background: "#7FAF8E",
    color: "#FFFFFF",
    border: "none",
    padding: "10px 14px",
    borderRadius: "8px",
    cursor: "pointer",
    fontWeight: "bold",
  },
  secondaryButton: {
    background: "#2B2F2E",
    color: "#FFFFFF",
    border: "none",
    padding: "10px 14px",
    borderRadius: "8px",
    cursor: "pointer",
  },
  warningButton: {
    background: "#A66A2D",
    color: "#FFFFFF",
    border: "none",
    padding: "9px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    marginTop: "10px",
  },
  dangerButton: {
    background: "#8B0000",
    color: "#FFFFFF",
    border: "none",
    padding: "9px 12px",
    borderRadius: "8px",
    cursor: "pointer",
    marginTop: "10px",
  },
  successText: {
    color: "#5F8F70",
    fontWeight: "bold",
  },
  warningText: {
    color: "#A66A2D",
    fontWeight: "bold",
  },
  mutedText: {
    color: "#5A5F5D",
    margin: "4px 0",
  },
  smallText: {
    color: "#5A5F5D",
    fontSize: "13px",
    lineHeight: "1.4",
  },
  finePrint: {
    color: "#5A5F5D",
    fontSize: "12px",
    lineHeight: "1.4",
    marginTop: "8px",
  },
  priceLine: {
    marginTop: "6px",
  },
};

export default styles;